# Generated by Django 4.2.8 on 2023-12-10 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure_box_app', '0003_alter_uploadedcontent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
