# Generated by Django 4.2.8 on 2023-12-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='file',
            field=models.FileField(default='default_filename.txt', upload_to='uploads/'),
        ),
    ]
