# Generated by Django 4.2.8 on 2023-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uploadedcontent_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcontent',
            name='is_public',
        ),
        migrations.AddField(
            model_name='uploadedcontent',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
